;;;;;;;;;; General ;;;;;;;;;;

[Intro Skip]
; Skips company logos and press any button screen.
Enabled = true

[Custom Resolution]
; Replaces "3840 x 2160" in-game with a custom resolution.
; You can leave width and height at 0 if you want your desktop resolution used.
Enabled = true
Width = 0
Height = 0

[Gameplay Camera]
; Adjust values to increase/decrease camera FOV and distance.
; i.e FOV = 1.25 = 25% wider
FOV = 1.0
Distance = 1.0

;;;;;;;;;; Ultrawide/Narrower ;;;;;;;;;;

[Fix HUD]
; Fixes cropped HUD and spans backgrounds (fades etc).
Enabled = true

[HUD Size]
; Adjusts the gameplay HUD and some menus to a specific aspect ratio.
; 0 = 16:9 (Default), 1 = 16:10, 2 = 21:9, 3 = Spanned (full)
HUDAspect = 0

[Fix FOV]
; Fixes cropped FOV at <16:9.
Enabled = true 

;;;;;;;;;; Graphical Tweaks ;;;;;;;;;;

[Shadow Quality]
; Set shadow resolution. Defaults: (Lighting Quality) Ultra = 2048, High = 1024, Standard = 256
Resolution = 2048

[Level of Detail]
; Modifies the distance at which objects pop-in. Increase to reduce object pop-in at the cost of performance.
Multiplier = 1.0

[Disable TAA]
; Set "Enabled" to "true" to disable temporal anti-aliasing.
Enabled = false

;;;;;;;;;; Experimental ;;;;;;;;;;

[Unlock Framerate]
; Removes framerate limit.
Enabled = false
